# Generated by Django 2.2.7 on 2020-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('domain', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('first_byte_time', models.FloatField(null=True)),
                ('complete_page_load_time', models.FloatField(null=True)),
                ('https_score', models.FloatField(null=True)),
                ('https_2_score', models.FloatField(null=True)),
                ('page_status_score', models.FloatField(null=True)),
                ('website_overall_score', models.PositiveIntegerField(default=0)),
                ('in_page_links', models.TextField(null=True)),
                ('ip', models.TextField(null=True)),
                ('doc_type', models.TextField(null=True)),
                ('encoding', models.TextField(null=True)),
                ('custom_error_page', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('robots_txt_info', models.TextField(null=True)),
                ('sitemap_info', models.TextField(null=True)),
                ('url_parameters', models.TextField(null=True)),
                ('broken_links_count', models.TextField(null=True)),
                ('discovered_pages', models.PositiveIntegerField(default=0)),
                ('trust_indicator_percent', models.TextField(null=True)),
                ('traffic_estimation', models.TextField(null=True)),
                ('traffic_rank', models.TextField(null=True)),
                ('page_speed_score', models.FloatField(null=True)),
                ('city', models.TextField(null=True)),
                ('isp', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('internet_company', models.TextField(null=True)),
                ('timezone', models.TextField(null=True)),
                ('region_name', models.TextField(null=True)),
            ],
        ),
    ]
