# Generated by Django 3.0.6 on 2020-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='domain',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
