# Generated by Django 3.0.6 on 2020-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20200524_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='discovered_pages',
            field=models.TextField(null=True),
        ),
    ]
