# Generated by Django 3.0.6 on 2020-05-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20200525_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyInfo',
            fields=[
                ('domain', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('total_js_files', models.FloatField(default=0)),
                ('js_difficulty', models.FloatField(default=0)),
                ('total_forms', models.FloatField(default=0)),
                ('form_difficulty', models.FloatField(default=0)),
            ],
        ),
    ]
