# Generated by Django 3.0.6 on 2020-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_difficultyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultyinfo',
            name='total_forms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='difficultyinfo',
            name='total_js_files',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
