# Generated by Django 3.0.6 on 2020-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_auto_20201008_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='website_overall_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
