# Generated by Django 3.0.6 on 2020-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_auto_20201008_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaininfo',
            name='trust_indicator_percent',
        ),
    ]
