# Generated by Django 3.1.2 on 2020-10-10 08:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_dashboard',
            fields=[
                ('dashboard_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('connected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_received', models.DateTimeField(default=datetime.datetime.now)),
                ('time_start_scraping', models.DateTimeField(default=None, null=True)),
                ('time_end_scraping', models.DateTimeField(default=None, null=True)),
                ('time_end', models.DateTimeField(default=None, null=True)),
                ('last_status', models.TextField(default='Request Received')),
                ('running_status', models.IntegerField(choices=[(1, 'Submitted'), (2, 'Scraping'), (3, 'Error'), (4, 'Complete'), (5, 'Interrupted')], default=0)),
                ('filename', models.TextField(blank=True, default=None, null=True)),
                ('was_downloaded', models.BooleanField(default=False)),
                ('is_download_ready', models.BooleanField(default=False)),
                ('connected_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user_dashboard')),
            ],
        ),
    ]
