# Generated by Django 3.1.2 on 2020-10-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
