# Generated by Django 3.1.2 on 2020-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_request_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(blank=True, default=None, null=True)),
                ('count', models.TextField(blank=True, default=None, null=True)),
                ('NETIS登録番号', models.TextField(blank=True, default=None, null=True)),
                ('技術名称', models.TextField(blank=True, default=None, null=True)),
                ('事後評価', models.TextField(blank=True, default=None, null=True)),
                ('受賞等_建設技術審査証明', models.TextField(blank=True, default=None, null=True)),
                ('受賞等_国土技術開発賞', models.TextField(blank=True, default=None, null=True)),
                ('受賞等_ものづくり日本大賞', models.TextField(blank=True, default=None, null=True)),
                ('受賞等_他機関の評価結果', models.TextField(blank=True, default=None, null=True)),
                ('事前審査_事後評価_試行実証評価', models.TextField(blank=True, default=None, null=True)),
                ('事前審査_事後評価_活用効果評価', models.TextField(blank=True, default=None, null=True)),
                ('事前審査_事後評価_事前審査', models.TextField(blank=True, default=None, null=True)),
                ('技術の位置付け_推奨技術', models.TextField(blank=True, default=None, null=True)),
                ('技術の位置付け_準推奨技術', models.TextField(blank=True, default=None, null=True)),
                ('技術の位置付け_評価促進技術', models.TextField(blank=True, default=None, null=True)),
                ('技術の位置付け_活用促進技術', models.TextField(blank=True, default=None, null=True)),
                ('level1', models.TextField(blank=True, default=None, null=True)),
                ('level2', models.TextField(blank=True, default=None, null=True)),
                ('level3', models.TextField(blank=True, default=None, null=True)),
                ('level4', models.TextField(blank=True, default=None, null=True)),
                ('技術会社', models.TextField(blank=True, default=None, null=True)),
                ('技術_担当部署', models.TextField(blank=True, default=None, null=True)),
                ('技術_担当者', models.TextField(blank=True, default=None, null=True)),
                ('技術部署_住所', models.TextField(blank=True, default=None, null=True)),
                ('技術部署_Tel', models.TextField(blank=True, default=None, null=True)),
                ('技術部署_FAX', models.TextField(blank=True, default=None, null=True)),
                ('技術部署_Email', models.TextField(blank=True, default=None, null=True)),
                ('技術部署_URL', models.TextField(blank=True, default=None, null=True)),
                ('営業会社', models.TextField(blank=True, default=None, null=True)),
                ('営業_担当部署', models.TextField(blank=True, default=None, null=True)),
                ('営業部署_担当者', models.TextField(blank=True, default=None, null=True)),
                ('営業部署_住所', models.TextField(blank=True, default=None, null=True)),
                ('営業部署_Tel', models.TextField(blank=True, default=None, null=True)),
                ('営業部署_FAX', models.TextField(blank=True, default=None, null=True)),
                ('営業部署_Email', models.TextField(blank=True, default=None, null=True)),
                ('営業部署_URL', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
