# Generated by Django 3.1.2 on 2020-10-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='scrapy_task_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='unique_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='running_status',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Scraping'), (3, 'Error'), (4, 'Complete'), (5, 'Interrupted'), (6, 'Unknown')], default=0),
        ),
    ]
